server:
  port: ${PORT:5010}

management:
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 5s
      show-details: "always"
  security:
    enabled: false
  endpoints:
    health:
      sensitive: false
    web:
      base-path: /
      exposure:
        include: 'health'

spring:
  application:
    name: AM Role Assignment E2E Tests
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

OrgRoleMappingUrl: ${ORM_URL:http://localhost:4098}
roleAssignmentAppUrl: ${ROLE_ASSIGNMENT_APP_URL:http://localhost:4096}

send-letter:
  url: ${SEND_LETTER_SERVICE_BASEURL:http://localhost:4021}
  enabled: ${SEND_LETTER_SERVICE_ENABLED:true}
  maxRetryAttempts: ${MAX_RETRY_ATTEMPTS:3}
